# Generated by Django 4.0.3 on 2022-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazarAdi', models.CharField(max_length=100, null=True)),
                ('numara', models.CharField(max_length=100, null=True)),
                ('dersAdi', models.CharField(max_length=100, null=True)),
                ('juriler', models.CharField(max_length=100, null=True)),
                ('donem', models.CharField(max_length=100, null=True)),
                ('ozet', models.CharField(max_length=2500, null=True)),
                ('danisman', models.CharField(max_length=100, null=True)),
                ('anahtarKelimeler', models.CharField(max_length=100, null=True)),
                ('baslik', models.CharField(max_length=100, null=True)),
                ('ogretim', models.CharField(max_length=100, null=True)),
                ('pdf', models.FileField(null=True, upload_to='files/pdfs/')),
                ('hocaID', models.IntegerField(null=True)),
            ],
        ),
    ]
